config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
   resources :products do
     member do
       post :add_to_cart
     end
   end

   resources :carts do
     collection do
       delete :clean
     end
   end
  
  resources :cart_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

   has_many :cart_items
   has_many :products, through: :cart_items, source: :product

   def add_product_to_cart(product)
     ci = cart_items.build
     ci.product = product
     ci.quantity = 1
     ci.save
   end

  def clean!
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

   belongs_to :cart
   belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    is_admin
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	layout "admin"
	before_action :authenticate_user!
	before_action :admin_required

  def index
  	@products = Product.all
  end 

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def edit 
  	@product = Product.find(params[:id])
  end 

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.

  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/", alert: "You are not admin."
    end
  end

   helper_method :current_cart

   def current_cart
     @current_cart ||= find_cart
   end

   private

   def find_cart
     cart = Cart.find_by(id: session[:cart_id])
     if cart.blank?
       cart = Cart.create
     end
     session[:cart_id] = cart.id
     return cart
   end

end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
   before_action :authenticate_user!

   def destroy
     @cart = current_cart
     @cart_item = @cart.cart_items.find_by(product_id: params[:id])
     @product = @cart_item.product
     @cart_item.destroy

     flash[:warning] = "成功将 #{@product.title} 从购物车删除!"
     redirect_to :back
   end

   def update
     @cart = current_cart
     @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
      @cart_item.update(cart_item_params)
      flash[:notice] = "成功变更数量"
    else
      flash[:warning] = "数量不足以加入购物车"
    end

     redirect_to carts_path
   end

   private

   def cart_item_params
     params.require(:cart_item).permit(:quantity)
   end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clean
    current_cart.clean!
    flash[:warning] = "已清空购物车"
    redirect_to carts_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show 
  	@product = Product.find(params[:id])
  end 

  def add_to_cart
     @product = Product.find(params[:id])
     if !current_cart.products.include?(@product)
       current_cart.add_product_to_cart(@product)
     
       flash[:notice] = "你已成功将 #{@product.title} 加入购物车"
     else
     	flash[:warning] = "你的购物车内已有此物品"
     end 
       redirect_back fallback_location: root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Morning"
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning" 
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/products/edit.html.erb
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>


  <% if @product.image.present? %>
    <span>目前商品图</span> <br>
    <%= image_tag(@product.image.thumb.url) %>
  <% end %>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>


  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th width="100"> Options</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td>
          <%= product.id %>
        </td>
        <td>
          <%= link_to product_path(product) do %>
            <% if product.image.present? %>
              <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= product.title %>
        </td>
        <td>
          <%= product.price %>
        </td>
        <td>
          <%= link_to("Edit", edit_admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%= f.input :image, as: :file %>
  </div>

  <%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/carts/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to("清空购物车", clean_carts_path ,
           method: :delete , class: "pull-right",
            style: "text-decoration: underline;",
            data: { confirm: "你确定要清空整个购物车吗？"} )%>

    <h2> 购物车 </h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">商品资讯</th>
          <th>单价</th>
          <th>数量</th>
          <th>操作选项 </th>
        </tr>
      </thead>
      <tbody>

        <% current_cart.cart_items.each do |cart_item| %>
          <tr>
            <td>
              <%= link_to product_path(cart_item.product) do %>
                <% if cart_item.product.image.present? %>
                  <%= image_tag(cart_item.product.image.thumb.url, class: "thumbnail") %>
                <% else %>
                  <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
            </td>
            <td>
              <%= cart_item.product.price %>
            </td>
            <td>
              <%= form_for cart_item, url: cart_item_path(cart_item.product_id) do |f| %>
                <%= f.select :quantity, 1..cart_item.product.quantity %>
                <%= f.submit "更新", data: { disable_with: "Submiting..." } %>
              <% end %>
            </td>
            <td>
              <%= link_to cart_item_path(cart_item.product_id), method: :delete do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>

      </tbody>
    </table>

    <br>

    <div class="total clearfix">
      <span class="pull-right">
         <span> 
           <% sum = 0 %>
            <% current_cart.cart_items.each do |cart_item| %>
              <% if cart_item.product.price.present? %>
                <% sum = sum + cart_item.quantity * cart_item.product.price %>
              <% end %>
            <% end %>
            总计 <%= sum %> RMB
     </span>
      </span>
    </div>

    <hr>

    <div class="checkout clearfix">
      <%= link_to("确认结账", "#", method: :post, class: "btn btn-lg btn-danger pull-right") %>
    </div>
  </div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 JDStore
        <br>Design by yourname
        
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">JDStore </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active">
                <%= link_to("Products", products_path) %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                  <li>
                     <%= link_to carts_path do  %>
                        购物车 <i class="fa fa-shopping-cart"> </i> ( <%= current_cart.products.count %> )
                     <% end %>
                  </li>
                 <% if !current_user %>
                   <li><%= link_to("注册", new_user_registration_path) %> </li>
                   <li><%= link_to(content_tag(:i, '登入', class: 'fa fa-sign-in'), new_user_session_path) %></li>
                 <% else %>
                   <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                         Hi!, <%= current_user.email %>
                         <b class="caret"></b>
                     </a>
                     <ul class="dropdown-menu">
                      <% if current_user.admin? %>
                        <li>
                          <%= link_to("Admin 选单", admin_products_path ) %>
                        </li>
                      <% end %>
                         <li> <%= link_to(content_tag(:i, '登出', class: 'fa fa-sign-out'), destroy_user_session_path, method: :delete) %> </li>
                     </ul>
                   </li>
                 <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JDstore 后台</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render "common/navbar" %>
    <div class="row">
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
          <li> <%= link_to("Products", admin_products_path) %> </li>
        </ul>
      </div>
      <div class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>JDStore </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
             <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/products/index.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-xs-6 col-md-3">
      <%= link_to product_path(product) do %>
        <% if product.image.present? %>
          <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
        <% else %>
          <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
      <%= product.title %> ￥ <%= product.price %>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.image.present? %>
      <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
      <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>
  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>
    <div> 数量 : <%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
    <div class="pull-right">
      <% if @product.quantity > 0 %>
        <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-primary btn-lg btn-danger") %>
      <% else %>
        已销售一空，无法购买
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1> Hello World! </h1>